# Generated by Django 5.0 on 2026-08-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_devicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='water_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetryreading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetryreading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
