# Generated by Django 5.0 on 2026-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_telemetryreading_water_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_level', models.FloatField(default=33.0)),
                ('stop_level', models.FloatField(default=100.0)),
                ('auto_mode', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='device_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='is_executed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='device_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='telemetryreading',
            name='device_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='telemetryreading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device_id', 'is_executed'], name='api_devicec_device__f15382_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['-timestamp'], name='api_devicel_timesta_f904aa_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['device_id', '-timestamp'], name='api_telemet_device__7ffe2b_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['-timestamp'], name='api_telemet_timesta_1e023f_idx'),
        ),
    ]
