# Generated by Django 5.0 on 2026-09-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_waterthreshold_alter_devicecommand_device_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterThreshold',
        ),
        migrations.RemoveField(
            model_name='telemetryreading',
            name='motor_status',
        ),
    ]
