# Generated by Django 5.0 on 2026-09-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_waterthreshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='probe_100',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='probe_25',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='probe_50',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='probe_75',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
