# Generated by Django 5.0 on 2026-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_telemetryreading_probe_100_telemetryreading_probe_25_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='motor_running',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='motor_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='servo_angle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
