# Generated by Django 5.0 on 2026-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='probe_read_ago_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
